### ISSUE TITLE
Nested Types Not Converted in Type Mapping

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#1056]
## I'm submitting a...

<pre><code>
[ ] Regression 
[*] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Code

**Entity:** 

```

@ObjectType()
@Entity()
export class Order extends BaseEntity {

  @Field(type => Point)
  @ValidateNested()
  @Column('point')
  startPoint: Point;

  @Field(type => Point)
  @ValidateNested()
  @Column('point')
  endPoint: Point;

  @Field(type => Int)
  @IsInt()
  @IsPositive()
  @Column({ default: null })
  deliveryCharges: number;

}

```

**Point Interface:**

```
@ObjectType()
export class Point {
  @IsNumber()
  x: number;
  @IsNumber()
  y: number;
}

```

**OrderCreate InputType:** 

```
@InputType()
export class OrderCreate extends PickType(
  Order,
  [
    'endPoint',
    'startPoint',
    'deliveryCharges',
  ],
  InputType,
) {}

```

## Current behavior

The scalar properties are converted correctly into InputType but the nested PointType is not converted, Giving:

Error: Cannot determine a GraphQL input type for the "startPoint".

## Expected behavior

The Point Type should also be Converted 

## Environment

<pre><code>
Nest version: 7.4.1

 
For Tooling issues:
- Node version: 13.8  
- Platform: Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by all2pie** [comment]
Here you go: 

https://github.com/all2pie/nestjsGraphQLIssue

**Comment by kamilmysliwiec** [comment]
I've pulled your repo and I don't think this is an issue with the schema generator. `Toy` class is decorated as an `ObjectType` and - since it's being used by `Cat` which is an `ObjectType` as well - we cannot simply convert `Toy` to an input type as this would break the `Cat` type. Likewise, we cannot generate another `Toy` input type based on the object type as this would lead to the following error: `Schema must contain uniquely named types but contains multiple types named "Toy"`. To fix this, you should redefine this property and the `Toy` type using a different name to make sure these types won't collide with each other.
