### ISSUE TITLE
Document comments in GraphQL schema ignored and aren't shown in playground schema

### ISSUE THREAD

**Issue by danil-z** [nestjs/graphql#107]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Document comments in GraphQL schema ignored and aren't shown in playground schema.

## Expected behavior

Should be able to view documentation for types and mutation in playground schema view

## Minimal reproduction of the problem with instructions

```
$ grep -i graphql package.json
    "@nestjs/graphql": "^5.5.1",
    "@types/graphql": "^14.0.5",
    "graphql": "^14.1.0",
    "graphql-iso-date": "^3.6.1",
    "graphql-tools": "^4.0.3",
    "graphql-type-json": "^0.2.1",
```

## What is the motivation / use case for changing the behavior?

```
$ grep -i nest  package.json
    "@nestjs/common": "^5.5.0",
    "@nestjs/core": "^5.5.0",
    "@nestjs/graphql": "^5.5.1",
    "@nestjs/jwt": "^0.2.1",
    "@nestjs/passport": "^5.1.0",
    "@nestjs/typeorm": "^5.2.2",
    "@nestjs/testing": "^5.5.0",
```

## Environment

<pre><code>
Nest version: 5.5.0

 
For Tooling issues:
- Node version: 10.15
- Platform:  
Mac

Others:

</code></pre>

**Comment by danil-z** [comment]
it's similar to https://github.com/nestjs/graphql/issues/4
but it's not clear what is the solution

**Comment by tzkmx** [comment]
I'm having this issue too, it is suggested that using a very old graphql package version would solve the problem (0.11.7), but that crashed the start with a TypeError because `getIntrospectionQuery` is not available.

> it's similar to #4
> but it's not clear what is the solution

I'm working on a little demo of integration of @nestjs to handle our graphql endpoint, and it serves as a reproducible setup to asses the bug. In `src/graphql/types/hello.js` I'm putting comments above the fields, but they don't show up in the Playground.

tzkmx/nestjs-graphql-as-express-subapp@d355018eb7d047105e2b4b45124e8eea575743a6

**Comment by tzkmx** [comment]
> ... In `src/graphql/types/hello.js` I'm putting comments above the fields, but they don't show up in the Playground.

Fixed comments inclusion by enclosing between [docstrings `"""` above and below the field `"""`](https://www.apollographql.com/docs/graphql-tools/generate-schema.html#descriptions) and now the descriptions are showing without any trouble.

tzkmx/nestjs-graphql-as-express-subapp@4ce3232

**Comment by kamilmysliwiec** [comment]
Should this issue be closed then?
