### ISSUE TITLE
Question: Why does this module print a generated schema only to parse it again?

### ISSUE THREAD

**Issue by ThisIsMissEm** [nestjs/graphql#1077]
I've been spending a lot of time reading the nestjs/graphql code recently, and I'm really curious as to why nestjs generates a GraphQLSchema object, then prints it to a string, then parses it using graphql-tag, and then uses that value as the typedefs value?

https://github.com/nestjs/graphql/blob/ad38ca060ceca19f2f82ac1e55f35999ed25f824/lib/graphql.factory.ts#L65-L74

It seems like a horrible inefficiency and double handling of values; is this because there's no helper function to extract typedefs from a GraphQLSchema value?

**Comment by MichaelOlatunji** [comment]
I guess you should make a pull request

**Comment by StevenLangbroek** [comment]
@MichaelOlatunji I guess she's asking a question. Maybe there's a good reason for this, maybe there isn't.

**Comment by joseym** [comment]
@MichaelOlatunji oddly defensive, and unconstructive ...

**Comment by ThisIsMissEm** [comment]
@kamilmysliwiec do you know the answer to this question? I'm sure the code must be like this for a reason, but I'm not sure why.

**Comment by kamilmysliwiec** [comment]
Apologies for the delay. 

That's a very good question. The reason is mainly backward compatibility. Originally, `@nestjs/graphql` package supported only schema first approach, delegating the schema creation process to Apollo. Since we added the code first approach on top of that, we wanted to make sure the rest of the code (except for generating the schema based on the metadata collected through decorators) remains almost the same between 2 different approaches (schema and code first). In this case, the schema builder (in code first) generates the GraphQL schema, but it sets the `resolve()` function (for the majority of types) to `undefined`, leaving the responsibility to "connect" resolvers with types to the `makeExecutableSchema()` function, similarly to what we're doing for schema first, and that's pretty much it. Refactoring the existing implementation to simplify this process should be doable, but it might introduce side-effects and breaking changes that would be quite hard to track and as we don't have enough time to do it at the moment, we just left it as it is for now.

**Comment by ThisIsMissEm** [comment]
@kamilmysliwiec ah! okay! Thanks for the great informative response, that definitely makes sense. It may be worth adding a comment into the codebase linking to this for future devs, to save them having the same question.
