### ISSUE TITLE
What is GraphQL+Mongoose recommended folder structure?

### ISSUE THREAD

**Issue by ugglr** [nestjs/graphql#1365]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Cannot find a conclusive answer in the docs.

## Expected behavior

I would like to be able to read in the docs how to structure a project. 

## What is the motivation / use case for changing the behavior?

I think a lot of developers are looking at nest and clarifying docs is a great way of lowering the barrier of entry.

## Environment
- Nest.js + GraphQL + MongoDB/Mongoose

## Question
I been looking around blogs, video tutorials and trying several different approaches myself, and when referencing what I've found with the docs it's hard to make a conclusion of what's recommended by the project itself. 

I realise that it's good to let the devs have it in the way they want, but a big selling point with nest is that a dev can follow the guidelines, and boilerplate patterns which the project relies on. 

After investing quite a bit of hours into what I think is the correct structure I would discuss with other developers who also have been thinking of this, or has experience scaling a nest project themselves and what they found. Below, is the structure I landed on 👇

```
root
    | src
        | main.ts
        | app.module.ts 
        | app.service.ts
        | constants.ta
        | database
            | database.module.ts
            | database.provider.ts
        | users
            | users.module.ts
            | users.resolver.ts
            | users.service.ts
            | users.provider.ts
            | interfaces
                user.interface.ts
            | schemas
                user.schema.ts
            | inputs
                | create-user.input.ts
                | delete-user.input.ts
                | update-user.input.ts
                | ...
            | dto
                | get-user.dto.ts
                | get-users.dto.ts
                | ...
```

Some group folders together and make further sub-folders in them, for instance I've seen inside the `dto`-folder people making a `input`-folder and an `args`-folder. Further I've seen some people name it `foo.schema.ts` and some calls it `foo.model.ts`. I think whatever floats is fine, but what's the recommendation?

**Comment by kamilmysliwiec** [comment]
I've been working on adding the "Best practices" page to the docs a while ago but I temporarily dropped this idea due to a lack of time, apologise for that!

The structure you proposed looks great and it's definitely in line with Nest's recommendations.

> Some group folders together and make further sub-folders in them, for instance I've seen inside the dto-folder people making a input-folder and an args-folder

Your solution looks somewhat better, but this one isn't bad either so I'd say this one is up to people's preference.

> Further I've seen some people name it foo.schema.ts and some calls it foo.model.ts. I think whatever floats is fine, but what's the recommendation?

In this case, I would say it depends on whether you have any methods defined in your classes. If your class is nothing more than just a schema, then go ahead and use a "schema" suffix. If it does though (encapsulates any logic related to this particular class), then using "model" sounds better.

For such discussions, I would recommend using our [Discord](https://discord.gg/G7Qnnhy) channel (support). We are using GitHub to track bugs, feature requests, and potential improvements.
