### ISSUE TITLE
GraphQL scalars output type not determined when coming from node_modules/

### ISSUE THREAD

**Issue by johnnyomair** [nestjs/graphql#1386]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When using GraphQL scalars (e.g. `ID`) in resolvers placed inside a library (therefore imported from node_modules/), Nest fails to determine the output type:

```
Error: Cannot determine a GraphQL output type for the "simpleScalar". Make sure your class is decorated with an appropriate decorator.
```

Using a `String` works perfectly fine.

## Expected behavior

Nest correctly determines the output type.

## Minimal reproduction of the problem with instructions
https://github.com/johnnyomair/nestjs-graphql-scalar-demo

Steps
1. Build library `cd lib/ && npm install && npm run build`
2. Run application `cd test/ && npm install && npm start:dev`

## What is the motivation / use case for changing the behavior?

I can't use GraphQL scalars (`ID`, `Int` and `Float`) in my library package.

## Environment

<pre><code>
Nest version: 7.5.1 (@nestjs/graphql at 7.9.9)
 
For Tooling issues:
- Node version: 10.23.3
- Platform:  Mac
</code></pre>

Others:

Might be related to: https://github.com/nestjs/graphql/issues/781

**Comment by kamilmysliwiec** [comment]
Your `@nestjs/{...}` deps must be defined as **peer dependencies**. Otherwise, both your lib and application will have a dedicated, local copy of these packages in the `node_modules` folder (`lib/node_modules/@nestjs/graphql/{random-class}` !== `test/node_modules/@nestjs/graphql/{random-class}`).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
