### ISSUE TITLE
Can we make @nestjs/graphql compatible with webpack. 

### ISSUE THREAD

**Issue by andrew-talentfish** [nestjs/graphql#1388]
I have a serverless monorepo setup where nestjs/graphql has been causing issues.  Not just with monorepo, but anything that tries to bundle (minifies) the app using webpack.  This has been a reported issue in the past and I don't know why this hasn't been fixed, especially when a company needs to do production ci/cd.

The issues are on many levels.  Even if I make the nestjs/graphql and all it's libs external, there are always failures.  For example, "Failure: Cannot determine a GraphQL output type for the "type". Make sure your class is decorated with an appropriate decorator."

**Comment by kamilmysliwiec** [comment]
This package is compatible with webpack. If you're facing any problems, please, create an issue with a detailed description and the minimum reproduction repository.

Otherwise, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
