### ISSUE TITLE
Missing typescript types in the generated type definition file (d.ts) when using `createUnionType` function. 

### ISSUE THREAD

**Issue by cledson-wiser** [nestjs/graphql#1529]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When using code first approach,type definition files (d.ts) generated for Graphql unions using `createUnionType` function do not have all types defined in the source typescript file.

## Expected behavior
type definition files (d.ts) generated for unions created by `createUnionType` should have all the types as defined in the original typescript file. 

## Minimal reproduction of the problem with instructions
I created this [repo](https://github.com/cledson-wiser/nestjs-graphql-union-issue) with a simple graphql API with Unions and step by step instructions

## What is the motivation / use case for changing the behavior?
The missing types in the generated type declaration file (d.ts) are causing typing errors when I try to use them in other projects since the declaration file doesn't contain all the expected types.

## Environment

<pre><code>
@nestjs/graphql version: 7.10.6
 
For Tooling issues:
- Node version: 14.15.1
- Platform:  Mac

Others:
</code></pre>

**Comment by kamilmysliwiec** [comment]
Can you please share the error message you get and the generated `.d.ts` file output (in which the issue occurs)?

**Comment by cledson-wiser** [comment]
There is no error message actually, build happens without any errors, but the generated .d.ts file don't have all the Types defined in the union.

the README file of the [repo](https://github.com/cledson-wiser/nestjs-graphql-union-issue#see-that-the-generated-type-definition-file-dont-have-all-types-in-the-resulting-typescript-union) that I linked have both files, but to summarize:

this file: 
```typescript
import { createUnionType } from "@nestjs/graphql";
import { Book } from "./product-types/Book";
import { Computer } from "./product-types/Computer";
import { Ebook } from "./product-types/EBook";
import { Magazine } from "./product-types/Magazine";
import { TV } from "./product-types/Tv";

export const ProductUnion = createUnionType({
    name: "ProductUnion",
    types: () => [
        Book,
        Computer,
        TV,
        Magazine,
        Ebook
    ]
})
```
results in this type declaration file: 

```typescript
import { Book } from "./product-types/Book";
import { Computer } from "./product-types/Computer";
export declare const ProductUnion: Book | Computer;
``` 

As we can see not all types defined in the union are present in the declaration file, this issue seems to affect only the declaration file, the compiled javascript file is fine.

**Comment by Karibash** [comment]
This may not be a Nest.js problem, but a TypeScript problem.
As a workaround, you can add a const assertion to generate the correct declaration file.

The following is an actual example.
ProductUnion has a missing type, but ConstProductUnion has the correct type.
[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOEA8rkC8ycI6AfMhAB6QgAmAzsgGICuICYwA9iMgN4AoZMhAQA7sgAUAOjlwoAcwYAuYqQDaAXQCUa1AG5BAX0GDQkWIhQBVEDxAB5TF14M8lGhHpMoEOHS8ADboaFi4JOTahOro2hRCIiBwALYQagxgUKCKRiJg4arSOoQUhiZmBdjIAIJQUHDoAKJBEGngOHUN6BjV1LSMyH4BwaHsANYg3OIg8TFdjb0QGiCsKQBG0FpGVbb2vB793oPDgSAhsXNEAJIgmSRIS531jS1t3mB4ZGRGgjDsnAcyAQw0gdgcT3wRx8Q38ZwuTwmUxmZGiREi8SkwmQ3BcDiK4N4zlcdy+ABpBHpkISQF8BNi-GBWFA+ABldAbbhBKS4kkMGTJNIlOBMSJGUyCBBBEVMABC3G44wEpilMuQAGFuClMKxLMrJdKGExUAA1fWqo3IACycEUcAAXqAUPwVYamE11gqlS6zAg3GBkAAFKDcOisTg0mIg-xg-YgJZSRIiUSpdLIABEwdD4bANPTFOTyF2RSkJQIFA02MLInlioL1ZEmu1uug9Ybprb1ZtdsdYk7hY9Xs7Wgpxh0vz9dwDmqnWbDEbjUdBEBpCaTSVTakzIfnubj+arRcKalLpWQlYbNaHh8LTZ1ln7yY7N+T3YdTsfIkHdcPWmITEnTJR3HQQgA)

However, to use this workaround, it is necessary to add readonly to the generics of the following functions so that they can pass arrays with const assertions.
https://github.com/nestjs/graphql/blob/92e17a28ced7216e64b0277c3d0a075c77289fb0/packages/graphql/lib/type-factories/create-union-type.factory.ts#L43

**Comment by kamilmysliwiec** [comment]
@Karibash we should probably update the docs then - to instruct ppl to use `as const`. Would you like to create a PR?

**Comment by Karibash** [comment]
I'll give it a try.
