### ISSUE TITLE
GraphQL Federation Module doesn't pass request to context option

### ISSUE THREAD

**Issue by dsoffiantini** [nestjs/graphql#1555]
When using a federation gateway as defined in this documentation: https://docs.nestjs.com/graphql/federation#sharing-context, the service receiving the incoming request cannot apply a context property to the graphql module. 

Federated Service Setup:
```
GraphQLFederationModule.forRoot({
      autoSchemaFile: 'schema.graphql',
      context: ({ req }) => {
        // request is always undefined here
      },
    }),
```

This is the pattern defined by apollo here: https://www.apollographql.com/blog/backend/auth/setting-up-authentication-and-authorization-apollo-federation/, but because the incoming request is always null, you end up needing to do a hacky workaround and grab the context in the resolve and drill down to the raw headers.

Currently using:
```
"@nestjs/graphql": "^7.10.6",
"@nestjs/platform-fastify": "^7.6.17",
```

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by clayrisser** [comment]
I'm having this same issue with `7.10.6`

**Comment by clayrisser** [comment]
You can see my code at the link below.

https://github.com/clayrisser/example-graphback-nestjs/blob/master/src/modules/graphql/graphql.service.ts#L34

Context is an empty object `{}`.

I'm not sure if the following issue is related.

https://github.com/nestjs/graphql/issues/1205

**Comment by smolinari** [comment]
@clayrisser 

Hello. You really shouldn't post in Github like this. Because.....

1. This issue is about federation, which your code isn't using. So, your repro would just waste the dev's time.
2. To help you, you should bring your problem up in Nest's Discord server. https://discord.gg/TrES3tBN
4. If after discussion in Discord shows you have a bug/ issue, then you can post a _new issue_ here. 

Thanks for your understanding!

Scott
