### ISSUE TITLE
Apollo Server own middleware

### ISSUE THREAD

**Issue by fjcero** [nestjs/graphql#18]
Since `apollo-server-express` is not working in the Nest way, a new middleware, that adapts to the Exception handling of Nest should be created. The original issue was created in `@nestjs/nest` since the example in the documentation leads to use this library.

Related issue https://github.com/nestjs/nest/issues/556

**Comment by VMois** [comment]
Any updates on this issue? @fjcero

**Comment by fjcero** [comment]
@VMois didn't create the PR yet, didn't have enough time to work on refactors, but the link to the related issue leads to a functional workaround, maybe not the best, but works.

**Comment by VMois** [comment]
@fjcero I will see. Thank you.

**Comment by michaelbromley** [comment]
This seems pretty important because currently with Apollo Server 2, if you use the `formatError` method in the apollo config, you do not have access to the Express request or context, see https://github.com/apollographql/apollo-server/issues/1343

In my case I rely on the context to get hold of the i18n function to translate my error messages.

Having our own Nest-specific wrapper around Apollo's exception handling means we would not be limited by the Apollo `formatError` API.

**Comment by edevil** [comment]
Since apollographql/apollo-server#1343 has been closed is this still relevant?

**Comment by kamilmysliwiec** [comment]
I guess it can be closed now.
