### ISSUE TITLE
Incorrect setup documentation for GraphQL Code first approach

### ISSUE THREAD

**Issue by NaLLiFFuNT** [nestjs/graphql#195]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Any request to my resolver fails if i use wrong import. IDE proposed to use `type-graphql`
import {Query, Resolver} from 'type-graphql';
import {Query, Resolver} from '@nestjs/graphql';

## Expected behavior

Documentation should warn that `import {Query, Resolver} from 'type-graphql';` will not work out and i should use `import {Query, Resolver} from '@nestjs/graphql';`. If both import work it would be better.

## Minimal reproduction of the problem with instructions

create my first Resolver
```
import {Query, Resolver} from 'type-graphql';

@Resolver()
export class PingResolver {

    @Query(returns => String, {description: `just return 'pong' string`})
    ping () {
        return 'pong';
    }
}
```
## What is the motivation / use case for changing the behavior?

I followed by this doc. 
https://docs.nestjs.com/graphql/quick-start#code-first
I guess i should not install `type-graphql` if  `@nestjs/graphql` uses it under the hood.

## Another question
I reckon this should not be in config if i use `code first approach`
```js
  typePaths: ['./**/*.graphql'],
```

## Environment

<pre><code>
 "@nestjs/common": "^6.0.0",
    "@nestjs/core": "^6.0.0",
    "@nestjs/graphql": "^6.0.5",
    "@nestjs/platform-express": "^6.0.0",
    "apollo-server-express": "^2.4.8",
    "graphql": "^14.2.1",
    "graphql-tools": "^4.0.4",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^6.3.3",
    "type-graphql": "^0.17.1"

 
For Tooling issues:
- Node version: v11.9.0
- Platform:  Mac

Others:

</code></pre>

**Comment by LandazuriPaul** [comment]
I agree that the exposed decorators and functions can be tricky. Actually, I had the same problem with `@Query()` being exposed by the `@nestjs/common` package too. It's quite difficult I guess for package maintainers to change those names as they correspond to the exact feature they offer. But I also think that the documentation should warn about this ambiguousness. 

Besides, I strongly disagree on the fact that you shouldn't have to install [TypeGraphQL](https://typegraphql.ml) as it is a direct dependency of `@nestjs/graphql` **IF (and only IF)** you choose the code first approach. Because defining this package as a peer dependency of `@nestjs/graphql` would mean that you get the overload even if you go for the schema first approach. And by the way, that wouldn't make any sense for the Nest project to re-expose all the objects from TypeGraphQL. The `@Field()`, `@InputType()`, `@ArgsType()`, etc. decorators are very specific to the code first approach developed by the latter (and indeed very convenient) but they don't belong to `@nestjs/graphql`.

Finally, about the "other question" you asked, I also had this in mind. Is there any reason for the `typePath` definition here? Isn't the `autoSchemaFile` attribute making the first one silent? I'll open an issue on the documentation repo to ask about it.

**Comment by NaLLiFFuNT** [comment]
> Besides, I strongly disagree on the fact that you shouldn't have to install [TypeGraphQL](https://typegraphql.ml) as it is a direct dependency of `nestjs/graphql` **IF (and only IF)** you choose the code first approach. Because defining this package as a peer dependency of `nestjs/graphql` would mean that you get the overload even if you go for the schema first approach. And by the way, that wouldn't make any sense for the Nest project to re-expose all the objects from TypeGraphQL. The `@Field()`, `@InputType()`, `@ArgsType()`, etc. decorators are very specific to the code first approach developed by the latter (and indeed very convenient) but they don't belong to `nestjs/graphql`.
> 

I do not use `type-graphql` on my own, it is uses by `nestjs/graphql` as dependency. `nestjs/graphql` provide all tools I need to work with Graphql. Thus, i believe, i should not install `type-graphql`. 

if `type-graphql` was a peerDependency, i'd have to install it.

**Comment by kamilmysliwiec** [comment]
> Finally, about the "other question" you asked, I also had this in mind. Is there any reason for the typePath definition here? Isn't the autoSchemaFile attribute making the first one silent? I've opened an issue on the documentation repo to ask about it: nestjs/docs.nestjs.com/issues/339.

Fixed already.

> I agree that the exposed decorators and functions can be tricky. Actually, I had the same problem with @Query() being exposed by the nestjs/common package too. It's quite difficult I guess for package maintainers to change those names as they correspond to the exact feature they offer. And I also think that the documentation should warn about this ambiguousness.

I have create a new issue https://github.com/nestjs/docs.nestjs.com/issues/418
