### ISSUE TITLE
graphql-scalars not working with MercuriusFederationDriver

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Scalar validations are not applied when using `MercuriusFederationDriver`

### Minimum reproduction code

https://github.com/all2pie/mercurius-scalar-bug

### Steps to reproduce

1.  `npm i`
2.  `npm start:dev`
3.  Go to http://localhost:3000/graphiql
4. Do this query: 
``` gql
query {
  test(id: "abc")
}
```

### Expected behavior

The validations should be applied like when using `MercuriusDriver`

Check the comment in `app.module.ts` for the desired behavior 

### Package version

10.0.9

### Graphql version

`graphql`: 16.3.0
`apollo-server-fastify`: 8.4.4

### NestJS version

8.2.2

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by all2pie** [comment]
I don't have an idea of the root cause, it would be great if someone can work on it, otherwise I will look into it on weekend

**Comment by all2pie** [comment]
Not able to find free time for this. If someone can work on it that would be great

**Comment by kamilmysliwiec** [comment]
@Davide-Gheri would you like to give it a shot? 😄

**Comment by Davide-Gheri** [comment]
It seems that the problem is not exclusive to the `MercuriusFederationDriver` but also to `ApolloFederationDriver` since they both uses the `GraphQLFederationFactory` to generate a valid schema.

The `GraphQLFederationFactory` and `GraphQLFactory` are profoundly different and the Federation one does not keep around custom scalars if they are not specified as resolvers.

In short, to fix the issue, you have to add the custom scalars to the `resolvers` object while registering the `GraphQLModule`, as the [documentation](https://docs.nestjs.com/graphql/scalars#import-a-custom-scalar) suggests
```typescript
// app.module.ts
import { GraphQLObjectID } from 'graphql-scalars';

@Module({
  imports: [
    GraphQLModule.forRoot({
      driver: MercuriusFederationDriver,
      resolvers: {
        ObjectID: GraphQLObjectID,
      },
    }),
  ],
})
export class AppModule {}


// app.resolver.ts
import { GraphQLObjectID } from 'graphql-scalars';

@Resolver()
export class AppResolver {
  @Query(() => Boolean)
  test(@Args('id', { type: () => GraphQLObjectID }) id) {
    console.log('id', id);
    return true;
  }
}
```

**Comment by all2pie** [comment]
This works but it should also work without registering in resolvers, like in the case of `MercuriusDriver` because the `graphql-scalars` has a lot of scalers and I am using mono repo (workspaces) so I want to use them dynamically instead of declaring everyone in the module of each microservice
