### ISSUE TITLE
graphql playground not work!

### ISSUE THREAD

**Issue by RobinYang11** [nestjs/graphql#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/20513480/168973847-9e0512b0-1f65-4329-bf33-043906462487.png)

### Minimum reproduction code

none 

### Expected behavior

![image](https://user-images.githubusercontent.com/20513480/168973860-c9d027ae-fcdf-4428-820e-6e51dd19debe.png)

### Package version

^8.0.0

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### NestJS version

^8.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

![image](https://user-images.githubusercontent.com/20513480/168974051-7e8d3f99-8205-4ad0-9d73-81532fd01e9a.png)

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by sonofmagic** [comment]
I meet the same issue , and i think it may caused by the block of this host `cdn.jsdelivr.net` in china.

We china users can fetch neither `npm/@apollographql/graphql-playground-react@1.7.42/build/static/css/index.css` nor `npm/@apollographql/graphql-playground-react@1.7.42/build/static/js/middleware.js` in our network. 
The Chorme's console shows Error `net::ERR_CONNECTION_TIMED_OUT`.
Then as the title says: `graphql playground not work!`

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the Apollo repository.
