### ISSUE TITLE
How to use RESTDataSource ?

### ISSUE THREAD

**Issue by jogelin** [nestjs/graphql#229]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

I am using NestJS 6 and I would like to use graphql to map rest api. It seems that the best way is to use `RESTDataSource` but I didn't succeed because it should be registered and I don't know how to do it with Nest :s

More infos : https://www.apollographql.com/docs/apollo-server/features/data-sources

**Comment by kamilmysliwiec** [comment]
You can just follow this tutorial: https://www.apollographql.com/docs/apollo-server/features/data-sources

One thing to note: https://www.apollographql.com/docs/apollo-server/features/data-sources#accessing-data-sources-from-resolvers (*Accessing data sources from resolvers*) - instead of passing `dataSources` property to `ApolloServer` constructor, pass it to the `GraphQLModule.forRoot()` method.
