### ISSUE TITLE
@Args() default to parameter name

### ISSUE THREAD

**Issue by elijaholmos** [nestjs/graphql#2383]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current behavior of the `@Args` decorator is primarily used to resolve a single input argument by its name. 
For example, a mutation defined in SDL as
```gql
type Mutation {
  createCat(createCatInput: CreateCatInput): Cat
}
```
could have its `createCatInput` argument supplied to a resolver by specifying the name of the argument in the `@Args()` decorator:
```ts
@Mutation('createCat')
create(@Args('createCatInput') args: CreateCatDto): Promise<Cat> { ... }
 ```

However, there are many instances where mutations require multiple arguments, and this can lead to lengthy resolver method definitions:
```gql
type Mutation {
  updateCat(id: Int!, updateCatInput: UpdateCatInput!, someOptionalArg: String): Cat
}
```
```ts
@Mutation('updateCat')
update(@Args('id') id: number, @Args('updateCatInput') updateCatInput: UpdateCatDto, @Args('someOptionalArg') someOptionalArg?: string): Promise<Cat> { ... }
```

### Describe the solution you'd like

I propose that usage of the `@Args()` decorator without an argument passed into the decorator causes the decorator argument to default to the name of the parameter it is decorating. The "lengthy resolver definition" dilemma described above would then be simplified to the following:
```ts
@Mutation('updateCat')
update(@Args() id: number, @Args() updateCatInput: UpdateCatDto, @Args() someOptionalArg?: string): Promise<Cat> { ... }
```

I am aware that the current implementation of `@Args()` without a decorator argument is to return the entire `input` object. An `updateCat` mutation resolver with a single parameter of `@Args() args` would be an object with the structure:
```ts
{
    id: 0,
    updateCatInput: {},
    someOptionalArg: '',
}
```
Typescript has dissapointingly minimal support for function parameter destructuring, and many developers opt to use sequential named parameters over destrutured input objects. My feature request includes the rejection of the current `@Args()` default behavior in favor of implementing the above solution.

### What is the motivation / use case for changing the behavior?

The main motivation is to improve general code readability by eliminating redundancy. Since resolver method parameters are often named the same as the argument they are connected to, this feature request would serve to ultimately improve the nestjs development experience.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future. Just a bit more context for you: in order to retrieve argument names we'd have to stringify the function body (`.toString()`) and use regular expressions to extract them which is far from optimal and is also prone to errors in case you use bundlers like webpack to optimize code. Alternatively, we could add this functionality to the NestJS GraphQL CLI plugin but this would make apps that use the plugin vs those that don't use it differ even more than now (and this is already difficult to document and maintain).

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
