### ISSUE TITLE
@Field() midleware not running on @ArgsType() or @InputType()

### ISSUE THREAD

**Issue by dragosmc** [nestjs/graphql#2446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The behaviour described in the documentation under `Field middleware` indicates that the middlewares are driven by the `@Field()` decorator, but I found that they don't work for all types.

In other words, the middlewares only get called on `ObectType()` but not on `@ArgsType()` or `@InputType()`.

The code snippets are take from the main branch of this repo and the middleware is the one described in the documentation here https://docs.nestjs.com/graphql/field-middleware

### Minimum reproduction code

https://gist.github.com/dragosmc/1e59619831f78be9b3420f6e7affd928

### Expected behavior

The output to contain the output of all 3 for running the e2e tests that were modified with the middlewares in the gist.

```
 yarn test:e2e
```

### Package version

10.1.3

### NestJS version

10.1.3

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is intentional (`GraphQLField` supports declaring the `resolve` method, while `GraphQLInputField` does not - both classes come from the `graphql` package). Still, to make this behavior a bit more straightforward, we should probably throw an error (or at least log a warning down to the console) to inform users that middleware functions registered on the input/arg type field level will be ignored.

Would you like to create a PR for this issue?

**Comment by equal-matt** [comment]
@kamilmysliwiec - what is the intended solution for running middleware-like transformations on input/arg types? More than happy to do a quick docs PR, but I'm not sure what the message is.

**Comment by equal-matt** [comment]
https://github.com/graphql/graphql-js/issues/361 - continuing discussion about field middleware support for when I find this in the future.

**Comment by kamilmysliwiec** [comment]
let's track this here https://github.com/graphql/graphql-js/issues/361
