### ISSUE TITLE
CLI plugin breaks paths when used with webpack alias (windows)

### ISSUE THREAD

**Issue by enricobuehler** [nestjs/graphql#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The plugin breaks import paths when used in combination with webpack aliases. 
It seems to happen because webpack transforms the import paths to absolute paths, which start with the drive letter, e.g. `D:\...` and then the plugin suffixes this path with `./`. If really needed i can provide a minimal reproduction but since i know which code is responsible for the bug i thought it wouldn't help.

### Minimum reproduction code

-

### Steps to reproduce

1. Create nestjs project
2. Setup plugin and webpack with alias imports
3. Run the dev server
-> Import fails only for the files modified by the cli

### Expected behavior

Obviously the paths shouldn't break, however im not sure how to achieve this. In my case just removing the `./` suffix fixed it, could also provide a PR for this, but don't know about possible side effects. The suffix is added here: https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/plugin/utils/plugin-utils.ts#L112

### Package version

10.1.6

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.11.1

### NestJS version

9.2.1

### Node.js version

19.6.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
We need a reproduction repository to fix this issue

**Comment by enricobuehler** [comment]
Sure, here you go: https://github.com/enricobuehler/nestjs-graphql-paths-bug

**Comment by enricobuehler** [comment]
Just tested it on macOS, there the issue doesn't occur.

**Comment by all2pie** [comment]
@enricobuehler yes please it would be appreciated. 

You can also look into #2734  it might be related.

**Comment by mikejpeters** [comment]
I'm running into the same issue on Windows (but it works fine on Linux).

The linked pull request fixes the compilation errors on Windows but then breaks things on Linux:

```
ERROR in ***/example.input.ts 6:23-47
Module not found: Error: Can't resolve 'other.input' in '/home/***/example/dto'
Did you mean './other.input'?
```

I tried to figure out what's going on, it seems like `relativePath` is actually an absolute path on windows:

```ts
  let relativePath = posix.relative(posix.dirname(fileName), importPath);
  relativePath = relativePath[0] !== '.' ? './' + relativePath : relativePath;
```

When this code runs on Windows for example:

1. `importPath` is `'C:/Users/***/example.model'`
2. `posix.dirname(fileName)` evaluates to `'.'`
3. `path.posix.relative('.', 'C:/Users/***/example.model')` evaluates to `'C:/Users/***/example.model'`

It seems like maybe the problem here is using `path.posix.relative` instead of `path.relative`? But I'm only guessing and kinda out of my depth here.

My hacky fix for now is to modify it to only prefix the path if it actually is relative:
```ts
  relativePath = !path.isAbsolute(relativePath) && relativePath[0] !== '.'` ? './' + relativePath : relativePath;
````

**Comment by kamilmysliwiec** [comment]
Perhaps we should include your hacky fix as a temporary solution to this issue, WDYT? @mikejpeters Would you like to create a PR for this?

**Comment by mikejpeters** [comment]
Yeah I can probably give it a shot this weekend if no-one else can do it in the meantime. I would like to try maybe adding some tests for Linux and Windows filepaths as well since it seems easy to fix one but break the other
