### ISSUE TITLE
Interceptor doesn't get all resolved properties

### ISSUE THREAD

**Issue by jogelin** [nestjs/graphql#320]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
I would like to be able to get resolved data. To put a `post script` when data are resolved.

To do so, I tried use an interceptor on resolvers to get data that resolvers are sending back. But the interceptor only get data returned by the query method and not all data resolved by other `@ResolveProperty` methods...

## Expected behavior
I would like to receive the real data returned to the client and not only the data returned by the Query.

## Minimal reproduction of the problem with instructions
```
@Resolver(type => Entity)
@UseInterceptors(EntityInterceptor)
export class EntityResolver {

  @Query(returns => [Entity])
  stationPlanList(): Observable<Plan[]> {
    return of([generateEntity()]);
  }

  @ResolveProperty()
  field(@Parent() entity: Entity): string {
    return 'blabla';
  }
}
```

```
export interface Response<T> {
  data: T;
}

@Injectable()
export class StationPlanInterceptor<T> implements NestInterceptor<T, Response<T>> {
  intercept(context: ExecutionContext, next: CallHandler): Observable<Response<T>> {
    return next.handle().pipe( tap(data => {
       console.log(data); --> the property field is not present !!
    }));
  }
}
```

## What is the motivation / use case for changing the behavior?
Be able to make an action after the resolvers are finishing there job !

## Environment

<pre><code>
    "@nestjs/common": "6.2.4",
    "@nestjs/core": "6.2.4",
    "@nestjs/graphql": "6.2.4",
</code></pre>

Maybe related to: #295 
Could be solved by: #263

**Comment by kamilmysliwiec** [comment]
Unfortunately, this is something that we cannot change at the `@nestjs/graphql` level. Our `GraphQLModule` is just a thin wrapper around the `ApolloServer` that creates a resolver map using reflection and decorators, providing composed context functions (instead of just "raw bindings" to method references) that allow you taking advantage of NestJS features (such as guards, interceptors etc). However, property resolvers are called apart from query methods and thus, we can't access the final response value (after aggregating all nested property resolver values) Even though this could be useful, it's entirely impossible with the existing implementation (and the primary idea of the package).

**Comment by michaelbromley** [comment]
@jogelin I had a similar requirement - I have to perform a transformation on the final result before it is returned to the client. The way I did it is by using the Apollo Server `GraphQLExtension` system. 

However, this is being deprecated in favour of the new Apollo Server plugin system introduced in v2.2. It is currently undocumented, but you can see an open docs PR here, which gives you the idea of how to use it: https://github.com/apollographql/apollo-server/pull/2008

Hope that helps!
