### ISSUE TITLE
Entity named Subscription breaks ResolveProperty

### ISSUE THREAD

**Issue by raydirty** [nestjs/graphql#462]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When naming an entity `Subscription` all services and decorated parameters are undefined.

```ts
@Resolver(of => Subscription)
export class SubscriptionResolver {
  constructor(private readonly subscriptionService: SubscriptionService) {}

  @ResolveProperty('child')
  child(@Root() subscription: Subscription): string {
    console.log(this, subscription); // subscription and this.subscriptionService is undefined
    return this.subscriptionService.getTest(); // Cannot read property 'getTest' of undefined
  }
}
```

## Expected behavior

The values shouldn't be undefined

## Minimal reproduction of the problem with instructions

* Git Repo: https://github.com/raydirty/nestjs-resolver-bug

## Environment

<pre><code>
platform-express version : 6.9.0
graphql version          : 6.5.3
common version           : 6.9.0
core version             : 6.9.0

</code></pre>

**Comment by SawyerHopkins** [comment]
I am actually experiencing this issue with any use case for `ResolveProperty`. 

Starting here when NestJS/GraphQL interacts with Type-GraphQL
https://github.com/nestjs/graphql/blob/d45f5b3fd0992c360b2099d89881350cae545876/lib/graphql-schema-builder.ts#L24

Which can be followed to here
https://github.com/MichalLytek/type-graphql/blob/ac2bded5154d14886c987fb8709805c040582c4e/src/schema/build-context.ts#L82

Since there is not container being passed, it just creates an new container with no instances in it. Setting a breakpoint
we can see that ResolveProperty enters gets resolved here
https://github.com/MichalLytek/type-graphql/blob/ac2bded5154d14886c987fb8709805c040582c4e/src/resolvers/create.ts#L29

Looking a few lines up we can see that container comes from the build context which was initialized as an empty container. Just to sanity check we can debug into that
https://github.com/MichalLytek/type-graphql/blob/ac2bded5154d14886c987fb8709805c040582c4e/src/utils/container.ts#L24

And we see that the container creates a new instance of the class, which results in inject parameters being undefined.

**Comment by kamilmysliwiec** [comment]
Aside from this issue, what's the reason for naming any object type "Subscription". Isn't it going to create a lot of confusion (and potential type collisions in the generated GraphQL schema?)

**Comment by dleitee** [comment]
I had the same problem here (and it was hard to discover what was going on).

So I think it would be good to have a Note on the docs alerting for that.

What do you think guys?

ps: it might happen with Query, Mutation and so on.

**Comment by kamilmysliwiec** [comment]
Creating an object type called either Subscription, Query, or Mutation will surely lead to errors because they collide with GraphQL operation types.
