### ISSUE TITLE
Nests's @Module should have a "resolvers" property alongside "controllers" for people who use GraphQL 

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/graphql#645]
## Issue
I have a slight issue when declaring which GraphQL Resolvers should be used in the module. Not a functional issue, rather aesthetic one. Currently Resolvers have to be declared as providers to activate them, which I don't think makes sense, as you cannot (or should not) actually inject them to use them in any other part of the app. Resolvers in GraphQL API's are the equivalent of Controllers in REST API's.

## Solution
It would be really nice to have a `resolvers` property introduced in `@Module` decorator's options so instead of 
```
@Module({
   providers: [PostService, PostResolver]
})
export class PostsModule {}
```
I can do
```
@Module({
  providers: [PostService],
  resolvers: [PostResolver] // this is new
})
export class PostsModule {}
```
In the same way we use when not using GraphQL:
```
@Module({
  providers: [PostService],
  controllers: [PostController]
})
export class PostsModule {}
```

And ideally have a warning thrown when I try to use a `@Resolver` class as a provider. Apart from that I think the functionality can stay the same.

## Motivation
GraphQL Resolvers are basically the equivalent of REST Controllers and therefore the method we use to register them should be similar. Using `providers` feels wrong and can make the code look a bit messy in module declarations at times.

**Comment by kamilmysliwiec** [comment]
We've already discussed this issue in the past. `@nestjs/graphql` has been originally published outside of `nest` monorepo. Hence, `nest` package is not even aware of the fact, that this library exists. We can't add an extra property to the `@Module()` decorator which will be used exclusively by a single library. The only thing we could do is to use `controllers` property instead of `providers`.  However, this would be confusing because - following this idea - we would have to separate out resolvers (controllers?), scalars (created as classes - providers?), plugins (added in this PR https://github.com/nestjs/graphql/pull/634, providers?), etc., which would create even more confusion. Therefore, we decided to stick to the existing solution.
