### ISSUE TITLE
Dataloader or another method to resolve n+1 problem

### ISSUE THREAD

**Issue by zerox12311** [nestjs/graphql#94]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

I want to use dataloader to resolve n+1 problem , I has seen the issue, but I had no idea.

## Expected behavior

@kamilmysliwiec say will publish a small chapter in the docs about integration with DataLoader, but I haven't found it.....
Does anyone had resolve n+1 problem??

## Environment

<pre><code>
Nest version: 5.4.0
Nest graphql version: 5.4.0
apollo-server-express version: 2.3.1

 
For Tooling issues:
- Node version: 11.3.0
- Platform:  Windows

Others:

</code></pre>

**Comment by rgolea** [comment]
@zerox12311 You can set it in context when you are using the GrapqhlModule or you can also generate it inside a middeware and generate it on every request.
Good luck with it!

**Comment by biels** [comment]
I have implemented the dataloader in a project for the critical queries. I can share the code if you are interested. It uses interceptors and uses the context to provide the dataloaders. However, I think my implementation is far from ideal since it breaks most of nest and graphql semantics. It forces me to predict how resolvers will be executed in the queries that typically hit my server, which defeats the purpose of having a graphql api. 
I would like to (and I am willing to contribute with my experience) implement it natively into @nestjs/graphql with decorators or even by default. In my opinion, solving the n+1 problem is something that is needed in every graphql server, I cannot think of a use case where I would want to leave that out intentionally.

**Comment by kamilmysliwiec** [comment]
Duplicate of #20

**Comment by zerox12311** [comment]
> I have implemented the dataloader in a project for the critical queries. I can share the code if you are interested. It uses interceptors and uses the context to provide the dataloaders. However, I think my implementation is far from ideal since it breaks most of nest and graphql semantics. It forces me to predict how resolvers will be executed in the queries that typically hit my server, which defeats the purpose of having a graphql api.
> I would like to (and I am willing to contribute with my experience) implement it natively into @nestjs/graphql with decorators or even by default. In my opinion, solving the n+1 problem is something that is needed in every graphql server, I cannot think of a use case where I would want to leave that out intentionally.

Yes! I am interested in it!
Can you share you code ?

**Comment by nguyenviettuananh** [comment]
@biels 
Can you share me your code that implemented data loader with graphQLModule?

**Comment by marcelriegr** [comment]
> @biels
> Can you share me your code that implemented data loader with graphQLModule?

Would also love to see that

**Comment by jogelin** [comment]
@biels 
Could share it to me toot ?

**Comment by crd13** [comment]
@biels Can you share your code? please
